version: 2.1
jobs:
  build_and_test:
    working_directory: ~/project/src
    docker:
      - image: circleci/php:7.3.10-stretch-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret

    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: composer依存関係をインストール
          command: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-

      - run:
          name: node_modules依存関係をインストール
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: .envファイルを復元
          command: echo $ENV_FILE | base64 --decode > .env

      - run:
          name: PDOエクステンションのインストール
          command: sudo docker-php-ext-install pdo_mysql

      - run:
          name: マイグレーションを実行
          command: php artisan migrate --env=testing --force

      - run: mkdir -p test_results

      - run:
          name: テストを実行
          command: ./vendor/bin/phpunit --testdox-xml test_results/phpunit/result.xml --coverage-html=coverage

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results

      - store_artifacts:
          path: coverage

workflows:
  main:
    jobs:
      - build_and_test
